### ISSUE TITLE
無效

### ISSUE THREAD

**Issue by bowen99** [Kaguya233qwq/nonebot_plugin_sky#1]
在發送群中發送光遇每日攻略並不會有任何消息

**Comment by Kaguya233qwq** [comment]
> 在發送群中發送光遇每日攻略並不會有任何消息

请提供后台报错的日志供排查

**Comment by bowen99** [comment]
[D 221115 16:07:44 nonebot_plugin_autohelp:72] msg: 光遇每日攻略
[D 221115 16:07:44 nonebot_plugin_autohelp:75] patt.findall(msg) False, return...
11-15 16:07:44 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_autohelp.nonebot_plugin_autohelp) running complete
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 2...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 4...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 5...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 12...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 13...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 50...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 90...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 100...
11-15 16:07:44 [DEBUG] nonebot | Checking for matchers in priority 999...
11-15 16:07:44 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_xiuxian.command)
11-15 16:07:44 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_xiuxian.command)
11-15 16:07:44 [DEBUG] nonebot | Running handler Dependent(call=_)
11-15 16:07:44 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_xiuxian.command) running complete
11-15 16:07:44 [DEBUG] nonebot | Stop event propagation

**Comment by Kaguya233qwq** [comment]
你难道没有设置命令前缀吗，默认是“/”

**Comment by bowen99** [comment]
命令前綴我有設置,/命令也試過

**Comment by Kaguya233qwq** [comment]
那我就不晓得了，我的插件本身是没有问题的，直接导入就能用。
