### ISSUE TITLE
能否基于Yunzai-Bot

### ISSUE THREAD

**Issue by Tloml-Starry** [Kaguya233qwq/nonebot_plugin_sky#11]
能否基于Yunzai-Bot写一个复刻类的单JS插件

**Comment by Kaguya233qwq** [comment]
如果是插件移植的话贴上项目原地址后随便，但开发或移植插件到nonebot以外的任何框架并不属于我的工作范畴。

**Comment by Tloml-Starry** [comment]
> 

好的，谢谢您的答复

**Comment by Kaguya233qwq** [comment]
Yunzaibot可以兼容nb插件，安装方法详见Yunzai文档

**Comment by Tloml-Starry** [comment]
> Yunzaibot可以兼容nb插件，安装方法详见Yunzai文档

谢谢您的提醒，我已知晓，只是想优化一点，并不是所有人都会装py也会嫌麻烦，感谢

**Comment by Algar233** [comment]
基于Yunzai-Bot的光遇插件https://gitee.com/Tloml-Starry/SKY-GuangYu-plugin

**Comment by Tloml-Starry** [comment]
谢谢😂这正是我正在编写的插件



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月31日 12:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kaguya233qwq/nonebot_plugin_sky] 能否基于Yunzai-Bot (Issue #11) |

基于Yunzai-Bot的光遇插件https://gitee.com/Tloml-Starry/SKY-GuangYu-plugin
