### ISSUE TITLE
有适配微信端的想法吗？

### ISSUE THREAD

**Issue by Baoer1** [Kaguya233qwq/nonebot_plugin_sky#2]
用nonebot2的ntchat适配器试了下：
11-17 21:40:59 [SUCCESS] nonebot | ntchat wxid_*** | [MT_RECV_TEXT_MSG]: Message 4869138679324892334 from wxi
d_***@[群:***@chatroom]: 光遇今日攻略
11-17 21:40:59 [DEBUG] nonebot | Checking for matchers in priority 1...
11-17 21:40:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_sky)
11-17 21:40:59 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_sky)
11-17 21:40:59 [DEBUG] nonebot | Running handler Dependent(call=_)
11-17 21:40:59 [DEBUG] nonebot | Handler Dependent(call=_) skipped
11-17 21:40:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_sky) running complete

**Comment by Kaguya233qwq** [comment]
目前本插件的逻辑确实是基于gocq编写的，微信的适配器我还没有用过。如果用户需求多的话未来有可能移植
