### ISSUE TITLE
插件pypi打包问题

### ISSUE THREAD

**Issue by lgc2333** [Kaguya233qwq/nonebot_plugin_sky#3]
![Screenshot_20221118-215345](https://user-images.githubusercontent.com/59048777/202720995-d920a686-a626-4fbc-bb77-65674e6c7974.png)

**Comment by Kaguya233qwq** [comment]
这是想做什么

**Comment by Kaguya233qwq** [comment]
意思是，我pipy上传的包不全是嘛哦我知道了蟹蟹
