### ISSUE TITLE
有没有渠道可以获得今日红石/黑石是几点场

### ISSUE THREAD

**Issue by tom-snow** [Kaguya233qwq/nonebot_plugin_sky#5]
如上，破碎季结束后时间很乱，想知道今天是几点场，如果可以的话最好可以在开始的时候发通知。

**Comment by Kaguya233qwq** [comment]
目前据各大光遇博主的发文可知，落石降落时间在变化，只能根据自己的经验进行预估，和游戏内可能有些出入。所以定时提醒也没有太大意义。但未来的版本将加入落石点的单独查询功能来展示博主的预测结果。

**Comment by VincentZyu233** [comment]
https://vincentzyu.top/

**Comment by Kaguya233qwq** [comment]
根据我目前获取到的信息，这是可以实现的。因为红黑石的掉落从周一到周日具有周期性，由此可以开发一个"红黑石掉落"推送功能。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月23日(周六) 上午7:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Kaguya233qwq/nonebot_plugin_sky] 有没有渠道可以获得今日红石/黑石是几点场 (Issue #5)




 
https://vincentzyu.top/
